#!/usr/bin/env python
import json
import os

import mysql
from mysql.connector import errorcode

from src.db import DbConnector

print("=============== Project Setup =================")
print("Let's set up the database connection first")
host = input('host [default:127.0.0.1]: ') or "127.0.0.1"
db_name = input('db name [default:brainboxai_challenge]: ') or "brainboxai_challenge"
user = input('username [default:root]: ') or "root"
password = input('password [default:'']: ') or ""

config = {
    "user": f"{user}",
    "password": f"{password}",
    "host": f"{host}",
    "database": f"{db_name}",
    "raise_on_warnings": True
}

with open(os.path.abspath(".db_config.json"), "w") as f:
    f.write(json.dumps(config, sort_keys=True, indent=4, separators=(',', ': '), default=str))

os.chmod(os.path.abspath("box-data-import"), 0o775)
os.chmod(os.path.abspath("box-data-report"), 0o775)

try:
    db = DbConnector()
    print('DB is set up and working')
except mysql.connector.Error as err:
    if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
        print("Something is wrong with your user name or password")
        exit(1)
    elif err.errno == errorcode.ER_BAD_DB_ERROR:
        try:
            cnx = mysql.connector.connect(user=user, password=password)
            cnx.cursor().execute("USE {}".format(db_name))
            cnx.close()
        except mysql.connector.Error as err:
            print("Database {} does not exists.".format(db_name))
            if err.errno == errorcode.ER_BAD_DB_ERROR:
                cnx.cursor().execute("CREATE DATABASE {} DEFAULT CHARACTER SET 'utf8'".format(db_name))
                print(f"Database {db_name} created successfully.")
                try:
                    db = DbConnector()
                    print(f'DB {db_name} is set up and working')
                    db.cnx.close()
                except mysql.connector.Error as err:
                    print(err)
                    exit(2)
            else:
                print(err)
                exit(3)
        else:
            print(err)
            exit(4)
    else:
        print(err)
        exit(5)

TABLES = {}
TABLES['boxes'] = (
    "CREATE TABLE `boxes` ("
    "  box_name VARCHAR(100) NOT NULL,"
    "  box_build_date DATETIME NOT NULL,"
    "  PRIMARY KEY ( box_name )"
    ") ENGINE=InnoDB")

TABLES['rpis'] = (
    "CREATE TABLE `rpis` ("
    "  mac_addr VARCHAR(100) NOT NULL,"
    "  purchase_date DATETIME NOT NULL,"
    "  cond VARCHAR(10) NOT NULL,"
    "  box_name VARCHAR(100),"
    "  PRIMARY KEY ( mac_addr ),"
    "  FOREIGN KEY ( box_name ) REFERENCES boxes( box_name )"
    ") ENGINE=InnoDB")

try:
    db = DbConnector()
    cursor = db.cnx.cursor()
    for table_name in TABLES:
        table_description = TABLES[table_name]
        try:
            print("Creating table {}: ".format(table_name), end='')
            cursor.execute(table_description)
        except mysql.connector.Error as err:
            if err.errno == errorcode.ER_TABLE_EXISTS_ERROR:
                print("already exists.")
            else:
                print(err.msg)
        else:
            print("OK")
    cursor.close()
    db.cnx.close()
except mysql.connector.Error as err:
    if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
        print("Something is wrong with your user name or password")
        exit(21)
    else:
        print(err)
        exit(22)
